services:
  games:
    image: quanosek/games:latest
    container_name: games
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
    command: sh -c "pnpm exec prisma migrate deploy && pnpm start"
    ports:
      - "${HOST_PORT}:3000"
    volumes:
      - data:/app/node_modules
    networks:
      - postgresql_default

networks:
  postgresql_default:
    external: true

volumes:
  data:
