services:
  games:
    container_name: games
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npx prisma migrate deploy && pnpm start"
    ports:
      - "${PORT}:3000"
    volumes:
      - /app/node_modules
    networks:
      - postgresql_default

networks:
  postgresql_default:
    external: true
